// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ETlib.Models;

[Table("Category")]
public partial class Category
{
    [Column("high", TypeName = "decimal(18, 0)")]
    public decimal High { get; set; }

    [Column("low", TypeName = "decimal(18, 0)")]
    public decimal Low { get; set; }

    [Key]
    [Column("ID")]
    public int Id { get; set; }
}