// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ETlib.Models;

public partial class PriceInterval
{
    [Column("high")]
    public double High { get; set; }

    [Column("low")]
    public double Low { get; set; }

    [Key]
    [Column("ID")]
    public int Id { get; set; }
}